### ISSUE TITLE
Request for example: generate client token

### ISSUE THREAD

**Issue by synw** [centrifugal/jscent#2]
Would it be possible to have an example with Nodejs that covers token generation for the js browser client?

I want to use Nodejs for some quick frontend prototyping but I can not figure out how to generate the token from the backend. It must be because I don't know Nodejs out of the very basics: an example would definitely help.

**Comment by FZambia** [comment]
@synw hello, will try to post it very soon! A bit busy at moment.

**Comment by synw** [comment]
Thanks ! Take your time

**Comment by FZambia** [comment]
@synw sorry for delay:

```javascript
var Client = require('jscent');

var token = new Client.Token("secret")
token.clientToken("42", "1488055494", "")
// output: '24d0aa4d7c679e45e151d268044723d07211c6a9465d0e35ee35303d13c5eeff'
```

**Comment by synw** [comment]
Thank you FZambia!
